# Generated by Django 4.2.30 on 2026-06-30 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("hscodes", "HS Code Search"),
                            ("vat", "VAT Calculator"),
                            ("invoice", "Invoice & Quotation Maker"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. tool_opened, hs_search_run, vat_calculated, invoice_printed",
                        max_length=64,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Random string generated client-side per browser session, not linked to identity.",
                        max_length=64,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code, derived server-side.",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Optional small payload, e.g. {'doc_mode': 'invoice'}",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool", "action", "created_at"],
                        name="event_event_tool_124aa5_idx",
                    )
                ],
            },
        ),
    ]
